# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Publicitário Developer'
description: " ̶U̶m̶ ̶c̶a̶r̶a̶ ̶f̶o̶r̶m̶a̶d̶o̶ ̶e̶m̶ ̶H̶u̶m̶a̶n̶a̶s̶ ̶q̶u̶e̶ ̶d̶e̶s̶a̶f̶i̶a̶-̶s̶e̶ ̶d̶i̶a̶r̶i̶a̶m̶e̶n̶t̶e̶ ̶e̶m̶ ̶E̶x̶a̶t̶a̶s̶ (Agora cursando Engenharia da Computação)"

# Author's info
author: 'James R. Moro'
# edit 'categories' in the front matter of every post to match this username
nickname: jamesrmoro
bio: 'Formado em Publicidade e Propaganda, resolveu fazer seu pé de meia na internet com foco em Wordpress e CSS. Além de ser um programador Front-End, curte cozinhar, desenhar e correr para ganhar medalhas para sua coleção. Estudante do 1º ano do Curso de Engenharia da Computação'
location: 'Jacareí, Brasil'
url: 'https://jamesrmoro.github.io/'
image: 'assets/images/jamesrmoro.jpg'

short_url: 'jamesrmoro.github.io'
google_analytics: UA-61679234-1
disqus: jamesrmoro
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: "/"

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate, jekyll-sitemap]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
# safe: false
# lsi: false
# username: jamesrmoro
repo: jamesrmoro.github.io
branch: master
# relative_source: ../jamesrmoro.github.io/
destination: jamesrmoro.github.io
production_url:  https://jamesrmoro.github.io
# source_url:      https://github.com/jamesrmoro/jekyll

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
